---

- name: test if nomad_server is set correctly
  ansible.builtin.assert:
    that:
      - nomad_server is defined
      - nomad_server is boolean
    quiet: yes

- name: test if nomad_bind_addr is set correctly
  ansible.builtin.assert:
    that:
      - nomad_bind_addr is defined
      - nomad_bind_addr is string
    quiet: yes
  when:
    - nomad_server | bool

- name: test if nomad_log_level is set correctly
  ansible.builtin.assert:
    that:
      - nomad_log_level is defined
      - nomad_log_level is string
      - nomad_log_level in [ "DEBUG", "INFO", "WARN" ]
    quiet: yes
  when:
    - nomad_server | bool

- name: test if nomad_data_dir is set correctly
  ansible.builtin.assert:
    that:
      - nomad_data_dir is defined
      - nomad_data_dir is string
    quiet: yes
  when:
    - nomad_server | bool

- name: test if nomad_advertise_addr is set correctly
  ansible.builtin.assert:
    that:
      - nomad_advertise_addr is defined
      - nomad_advertise_addr is string
    quiet: yes
  when:
    - nomad_server | bool
- name: test if nomad_server_bootstrap_expect is set correctly
  ansible.builtin.assert:
    that:
      - nomad_server_bootstrap_expect is defined
      - nomad_server_bootstrap_expect is number
    quiet: yes
  when:
    - nomad_server | bool

- name: test if nomad_server_bootstrap_expect is set correctly
  ansible.builtin.assert:
    that:
      - nomad_server_bootstrap_expect is not divisibleby 2
    fail_msg: "This parameter should be odd, it's even."
    quiet: yes
  when:
    - nomad_server | bool

- name: test if nomdad_agent is set correctly
  ansible.builtin.assert:
    that:
      - nomad_client is defined
      - nomad_client is boolean
    quiet: yes
