---
# tasks file for nomad

- name: import assert.yml
  import_tasks: assert.yml
  run_once: yes
  delegate_to: localhost

- name: create /etc/nomad.d
  ansible.builtin.file:
    path: /etc/nomad.d
    state: directory
    mode: "0750"
    owner: nomad
    group: nomad

- name: capture unwanted files
  ansible.builtin.find:
    paths: /etc/nomad.d
    file_type: file
    excludes:
      - "base.hcl"
      - "client.hcl"
      - "server.hcl"
      - "nomad.env"
  register: unwanted_files

- name: delete unwanted files
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ unwanted_files['files'] }}"

- name: copy nomad environment file
  ansible.builtin.template:
    src: nomad.env.j2
    dest: /etc/nomad.d/nomad.env
    mode: "0640"
    owner: nomad
    group: nomad
  notify:
    - restart nomad

- name: configure genaral nomad options
  ansible.builtin.template:
    src: base.hcl.j2
    dest: /etc/nomad.d/base.hcl
    mode: "0640"
    owner: nomad
    group: nomad
  notify:
    - restart nomad

- name: configure nomad server
  ansible.builtin.template:
    src: server.hcl.j2
    dest: /etc/nomad.d/server.hcl
    mode: "0640"
    owner: nomad
    group: nomad
  notify:
    - restart nomad
  when:
    - nomad_server | bool

- name: configure nomad agent
  ansible.builtin.template:
    src: client.hcl.j2
    dest: /etc/nomad.d/client.hcl
    mode: "0640"
    owner: nomad
    group: nomad
  notify:
    - restart nomad
  when:
    - nomad_agent | bool

- name: start nomad
  ansible.builtin.service:
    name: nomad
    state: started
    enabled: yes

- name: determine nomad leader
  ansible.builtin.set_fact:
    nomad_leader: "{{ nomad_advertise_addr }}"
  run_once: yes
  when:
    - nomad_server | bool

- name: list server members
  ansible.builtin.command:
    cmd: nomad server members
  register: nomad_list_server_members
  changed_when: no
  when:
    - nomad_server | bool

- name: join nomad leader
  ansible.builtin.command:
    cmd: nomad server join {{ nomad_leader }}:4648
  register: nomad_join_nomad_leader
