---
# tasks file for nomad

- name: import assert.yml
  import_tasks: assert.yml
  run_once: yes
  delegate_to: localhost

- name: create /etc/nomad.d
  ansible.builtin.file:
    path: /etc/nomad
    state: directory
    mode: "0750"
    owner: nomad
    group: nomad

- name: configure nomad
  ansible.builtin.template:
    src: nomad.hcl.j2
    dest: /etc/nomad.d/nomad.hcl
    mode: "0640"
    owner: nomad
    group: nomad
  notify:
    - restart nomad

- name: start nomad
  ansible.builtin.service:
    name: nomad
    state: started
    enabled: yes
