---
# tasks file for nomad

- name: import assert.yml
  import_tasks: assert.yml
  run_once: yes
  delegate_to: localhost

- name: create /etc/nomad.d
  ansible.builtin.file:
    path: /etc/nomad.d
    state: directory
    mode: "0750"
    owner: nomad
    group: nomad

- name: capture unwanted files
  ansible.builtin.find:
    paths: /etc/nomad.d
    file_type: file
    excludes:
      - base.hcl
      - client.hcl
      - server.hcl
      - nomad.env
  register: unwanted_files

- name: delete unwanted files
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ unwanted_files['files'] }}"

- name: delete server config if it is not defined
  ansible.builtin.file:
    path: /etc/nomad.d/server.hcl
    state: absent
  when:
    - not nomad_server
  notify:
    - restart nomad

- name: delete client config if it is not defined
  ansible.builtin.file:
    path: /etc/nomad.d/client.hcl
    state: absent
  when:
    - not nomad_client
  notify:
    - restart nomad
  
- name: copy nomad environment file
  ansible.builtin.template:
    src: nomad.env.j2
    dest: /etc/nomad.d/nomad.env
    mode: "0640"
    owner: nomad
    group: nomad
  notify:
    - restart nomad

- name: configure genaral nomad options
  ansible.builtin.template:
    src: base.hcl.j2
    dest: /etc/nomad.d/base.hcl
    mode: "0640"
    owner: nomad
    group: nomad
  notify:
    - restart nomad

- name: configure nomad server
  ansible.builtin.template:
    src: server.hcl.j2
    dest: /etc/nomad.d/server.hcl
    mode: "0640"
    owner: nomad
    group: nomad
  notify:
    - restart nomad
  when:
    - nomad_server | bool

- name: configure nomad agent
  ansible.builtin.template:
    src: client.hcl.j2
    dest: /etc/nomad.d/client.hcl
    mode: "0640"
    owner: nomad
    group: nomad
  notify:
    - restart nomad
  when:
    - nomad_client | bool

- name: start nomad
  ansible.builtin.service:
    name: nomad
    state: started
    enabled: yes
